import Head from "next/head";
import React from "react";
import Header from "./components/header";
import Footer from "./components/footer";
import PageTitle from "./components/About/pageTitle";
import AboutPage from "./components/About/aboutPage";
import FeaturePage from "./components/About/featurePage";
import Awards from "./components/About/awards";
import Team from "./components/About/team";
import AboutTestimonial from "./components/About/aboutTestimonial";

const about = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <PageTitle />
        <AboutPage />
        <FeaturePage />
        <Awards />
        <Team />
        <AboutTestimonial />
        <Footer />
      </main>
    </>
  );
};

export default about;
