import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "./components/header";
import Banner from "./components/Homepage/banner";
import Footer from "./components/footer";
import Partners from "./components/Homepage/partners";
import Testimonial from "./components/Homepage/testimonial";
import Appoinment from "./components/Homepage/appoinment";
import Services from "./components/Homepage/services";
import Data from "./components/Homepage/data";
import About from "./components/Homepage/about";
import Feature from "./components/Homepage/feature";

("use Client");

export default function Home() {
  return (
    <>
      <Head>
        <title>Novena Healthcare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header></Header>
        <Banner />
        <Feature />
        <About />
        <Data />
        <Services />
        <Appoinment />
        <Testimonial />
        <Partners />
        <Footer />
      </main>
    </>
  );
}
