import Head from "next/head";
import React from "react";
import Header from "./components/header";
import Footer from "./components/footer";
import PageTitle from "./components/Service/pageTitle";
import ServiceCards from "./components/Service/serviceCards";
import CtaPage from "./components/Service/ctaPage";
const about = () => {
  return (
    <>
      <Head>
        <title>Our Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <PageTitle />
        <ServiceCards />
        <CtaPage />
        <Footer />
      </main>
    </>
  );
};

export default about;
